# Generated by Django 4.0.6 on 2022-07-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinema', '0002_rename_actors_actor_rename_agents_agent_and_more'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='films',
            field=models.ManyToManyField(blank=True, default=None, to='sinema.film'),
        ),
    ]
