# Generated by Django 4.0.6 on 2022-07-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_films'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=None, max_length=11, unique=True),
            preserve_default=False,
        ),
    ]
