# Generated by Django 4.0.6 on 2022-07-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country_code',
            field=models.CharField(default='+98', max_length=3),
        ),
    ]
