# Generated by Django 4.0.6 on 2022-07-11 08:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ویرایش شده در')),
                ('title', models.CharField(db_index=True, max_length=250, unique=True, verbose_name='عنوان')),
                ('description', models.CharField(db_index=True, max_length=250, verbose_name='توضیحات')),
                ('keywords', models.CharField(db_index=True, max_length=250, verbose_name='کلمات کلیدی')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ویرایش شده در')),
                ('title', models.CharField(db_index=True, max_length=250, unique=True, verbose_name='عنوان')),
                ('description', models.CharField(db_index=True, max_length=250, verbose_name='توضیحات')),
                ('keywords', models.CharField(db_index=True, max_length=250, verbose_name='کلمات کلیدی')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ویرایش شده در')),
                ('title', models.CharField(db_index=True, max_length=250, unique=True, verbose_name='عنوان')),
                ('description', models.CharField(db_index=True, max_length=250, verbose_name='توضیحات')),
                ('keywords', models.CharField(db_index=True, max_length=250, verbose_name='کلمات کلیدی')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ویرایش شده در')),
                ('title', models.CharField(db_index=True, max_length=250, unique=True, verbose_name='عنوان')),
                ('description', models.CharField(db_index=True, max_length=250, verbose_name='توضیحات')),
                ('keywords', models.CharField(db_index=True, max_length=250, verbose_name='کلمات کلیدی')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ویرایش شده در')),
                ('title', models.CharField(db_index=True, max_length=250, unique=True, verbose_name='عنوان')),
                ('description', models.CharField(db_index=True, max_length=250, verbose_name='توضیحات')),
                ('keywords', models.CharField(db_index=True, max_length=250, verbose_name='کلمات کلیدی')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('abstract', models.TextField()),
                ('image', models.ImageField(upload_to='public/sinema/images/%Y/%M')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('age', models.PositiveSmallIntegerField(default=10)),
                ('imdb_score', models.FloatField(default=5.0)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ویرایش شده در')),
                ('title', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ویرایش شده در')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoundAndSubtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ویرایش شده در')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('sound_and_subtitle', models.FileField(upload_to='private/sinema/SoundAndSubtitle/')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ویرایش شده در')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('file', models.FileField(upload_to='private/sinema/video/')),
                ('sound_and_subtitle', models.ManyToManyField(related_name='video_sound_and_subtitle', to='sinema.soundandsubtitle')),
            ],
        ),
        migrations.AddIndex(
            model_name='soundandsubtitle',
            index=models.Index(fields=['name'], name='sinema_soun_name_09cbac_idx'),
        ),
        migrations.AddField(
            model_name='season',
            name='videos',
            field=models.ManyToManyField(related_name='season_video', to='sinema.video'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['title'], name='sinema_job_title_a4eeed_idx'),
        ),
        migrations.AddField(
            model_name='film',
            name='actors',
            field=models.ManyToManyField(related_name='film_actors', to='sinema.actors'),
        ),
        migrations.AddField(
            model_name='film',
            name='agents',
            field=models.ManyToManyField(related_name='film_agent', to='sinema.agents'),
        ),
        migrations.AddField(
            model_name='film',
            name='categorys',
            field=models.ManyToManyField(related_name='film_category', to='sinema.category'),
        ),
        migrations.AddField(
            model_name='film',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sinema.country'),
        ),
        migrations.AddField(
            model_name='film',
            name='season',
            field=models.ManyToManyField(related_name='film_season', to='sinema.season'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['name', 'slug'], name='sinema_coun_name_89ee37_idx'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sinema.category'),
        ),
        migrations.AddField(
            model_name='agents',
            name='job',
            field=models.ManyToManyField(related_name='agent_job', to='sinema.job'),
        ),
        migrations.AddIndex(
            model_name='actors',
            index=models.Index(fields=['name', 'slug'], name='sinema_acto_name_8083b3_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['name'], name='sinema_vide_name_4ab247_idx'),
        ),
        migrations.AddIndex(
            model_name='season',
            index=models.Index(fields=['name'], name='sinema_seas_name_bbee34_idx'),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['name'], name='sinema_film_name_50be71_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name', 'slug'], name='sinema_cate_name_89512e_idx'),
        ),
        migrations.AddIndex(
            model_name='agents',
            index=models.Index(fields=['name', 'slug'], name='sinema_agen_name_50a59a_idx'),
        ),
    ]
