# Generated by Django 4.0.6 on 2022-07-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinema', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actors',
            new_name='Actor',
        ),
        migrations.RenameModel(
            old_name='Agents',
            new_name='Agent',
        ),
        migrations.RemoveIndex(
            model_name='actor',
            name='sinema_acto_name_8083b3_idx',
        ),
        migrations.RemoveIndex(
            model_name='agent',
            name='sinema_agen_name_50a59a_idx',
        ),
        migrations.AddIndex(
            model_name='actor',
            index=models.Index(fields=['name', 'slug'], name='sinema_acto_name_16a7f8_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['name', 'slug'], name='sinema_agen_name_f17a11_idx'),
        ),
    ]
