# Generated by Django 4.0.6 on 2022-07-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinema', '0002_rename_actors_actor_rename_agents_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='description',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='actor',
            name='keywords',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='actor',
            name='title',
            field=models.CharField(db_index=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='description',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='agent',
            name='keywords',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='agent',
            name='title',
            field=models.CharField(db_index=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='category',
            name='keywords',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(db_index=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='description',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='country',
            name='keywords',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='country',
            name='title',
            field=models.CharField(db_index=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='film',
            name='keywords',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(db_index=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='soundandsubtitle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='soundandsubtitle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='sound_and_subtitle',
            field=models.ManyToManyField(blank=True, default=None, related_name='video_sound_and_subtitle', to='sinema.soundandsubtitle'),
        ),
        migrations.AlterField(
            model_name='video',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
