# Generated by Django 4.0.6 on 2022-07-11 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinema', '0004_alter_film_publish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='imdb_score',
            new_name='IMDB_score',
        ),
    ]
