# Generated by Django 4.0.6 on 2022-07-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinema', '0005_rename_imdb_score_film_imdb_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='videos',
        ),
        migrations.RemoveField(
            model_name='video',
            name='sound_and_subtitle',
        ),
        migrations.AddField(
            model_name='video',
            name='qulaity',
            field=models.PositiveSmallIntegerField(default=720),
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('film', models.ManyToManyField(related_name='part_videos', to='sinema.video')),
                ('sound_and_subtitle', models.ManyToManyField(blank=True, default=None, related_name='part_sound_and_subtitle', to='sinema.soundandsubtitle')),
            ],
        ),
        migrations.AddField(
            model_name='season',
            name='parts',
            field=models.ManyToManyField(related_name='season_part', to='sinema.part'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['name'], name='sinema_part_name_c5d3f0_idx'),
        ),
    ]
